#!/usr/bin/env python3
"""Check for and apply shared RERITE website navigation/style updates.

The upstream repository remains the source of truth. This script vendors a
small, deterministic subset into this repository and injects the shared navbar
into pages that already have a navigation bar.

Examples:
    python sync_rerite.py --check
    python sync_rerite.py --apply
    python sync_rerite.py --check --source-dir ../RRinTransportation.github.io
    python sync_rerite.py --apply --source-dir ../RRinTransportation.github.io

Exit codes:
    0: up to date, or updates applied successfully
    1: --check found updates
    2: fetch, validation, or file update error
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import stat
import subprocess
import sys
import tempfile
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parent
UPSTREAM_REPOSITORY = "RRinTransportation/RRinTransportation.github.io"
DEFAULT_REF = "main"

ASSET_DIR = ROOT / "assets" / "rerite"
NAVBAR_ASSET = ASSET_DIR / "navbar.html"
BASE_CSS_ASSET = ASSET_DIR / "rerite-base.css"
NAVBAR_CSS_ASSET = ASSET_DIR / "rerite-navbar.css"
MANIFEST_PATH = ASSET_DIR / "sync-manifest.json"

NAV_START = "<!-- RERITE_SHARED_NAV:START -->"
NAV_END = "<!-- RERITE_SHARED_NAV:END -->"
STYLES_START = "<!-- RERITE_SHARED_STYLES:START -->"
STYLES_END = "<!-- RERITE_SHARED_STYLES:END -->"

CSS_NAVIGATION_MARKER = "/* Navigation */"
CSS_CONTAINER_MARKER = "/* Container */"

REQUIRED_TARGETS = (
    ROOT / "index.html",
    ROOT / "stats.html",
    ROOT / "blog" / "templates" / "index.html",
    ROOT / "blog" / "templates" / "post.html",
)

GENERATED_HEADER = """/*
 * Generated by sync_rerite.py from RRinTransportation.github.io.
 * Do not edit this file directly; edit the upstream source and re-run sync.
 */

"""


class SyncError(RuntimeError):
    """A safe, user-facing synchronization failure."""


@dataclass(frozen=True)
class Snapshot:
    navbar: str
    styles: str
    commit: str
    ref: str
    source: str


def sha256_text(value: str) -> str:
    return hashlib.sha256(value.encode("utf-8")).hexdigest()


def github_headers() -> dict[str, str]:
    headers = {
        "Accept": "application/vnd.github+json",
        "User-Agent": "MOST-RERITE-sync",
        "X-GitHub-Api-Version": "2022-11-28",
    }
    token = os.environ.get("GITHUB_TOKEN") or os.environ.get("GH_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return headers


def request_text(url: str, *, headers: dict[str, str]) -> str:
    request = urllib.request.Request(url, headers=headers)
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return response.read().decode("utf-8")
    except urllib.error.HTTPError as error:
        rate_limit_hint = ""
        if error.code == 403:
            rate_limit_hint = " Set GITHUB_TOKEN or GH_TOKEN if GitHub rate-limited the request."
        raise SyncError(f"GitHub returned HTTP {error.code} for {url}.{rate_limit_hint}") from error
    except (urllib.error.URLError, TimeoutError, UnicodeDecodeError) as error:
        raise SyncError(f"Could not fetch {url}: {error}") from error


def load_remote_snapshot(ref: str) -> Snapshot:
    headers = github_headers()
    encoded_ref = urllib.parse.quote(ref, safe="")
    commit_url = (
        f"https://api.github.com/repos/{UPSTREAM_REPOSITORY}/commits/{encoded_ref}"
    )
    try:
        commit_data = json.loads(request_text(commit_url, headers=headers))
        commit = commit_data["sha"]
    except (json.JSONDecodeError, KeyError, TypeError) as error:
        raise SyncError("GitHub returned an invalid commit response.") from error
    if not isinstance(commit, str) or not re.fullmatch(r"[0-9a-fA-F]{40}", commit):
        raise SyncError("GitHub returned an invalid commit SHA.")

    raw_root = f"https://raw.githubusercontent.com/{UPSTREAM_REPOSITORY}/{commit}"
    navbar = request_text(f"{raw_root}/navbar.html", headers=headers)
    styles = request_text(f"{raw_root}/styles.css", headers=headers)
    return Snapshot(
        navbar=navbar,
        styles=styles,
        commit=commit,
        ref=ref,
        source=f"https://github.com/{UPSTREAM_REPOSITORY}/tree/{commit}",
    )


def git_output(source_dir: Path, *args: str) -> str:
    try:
        result = subprocess.run(
            ["git", "-C", str(source_dir), *args],
            check=True,
            capture_output=True,
            text=True,
        )
    except (FileNotFoundError, subprocess.CalledProcessError):
        return ""
    return result.stdout.strip()


def load_local_snapshot(source_dir: Path) -> Snapshot:
    source_dir = source_dir.expanduser().resolve()
    navbar_path = source_dir / "navbar.html"
    styles_path = source_dir / "styles.css"
    missing = [path.name for path in (navbar_path, styles_path) if not path.is_file()]
    if missing:
        raise SyncError(
            f"{source_dir} is missing required upstream file(s): {', '.join(missing)}"
        )

    commit = git_output(source_dir, "rev-parse", "HEAD") or "local-working-tree"
    relevant_status = git_output(
        source_dir, "status", "--short", "--", "navbar.html", "styles.css"
    )
    if relevant_status:
        commit = f"{commit}-dirty"

    source_ref = git_output(source_dir, "symbolic-ref", "--short", "HEAD")
    return Snapshot(
        navbar=navbar_path.read_text(encoding="utf-8"),
        styles=styles_path.read_text(encoding="utf-8"),
        commit=commit,
        ref=source_ref or "local-working-tree",
        source=str(source_dir),
    )


def normalize_project_base(value: str) -> str:
    value = value.strip()
    if not value.startswith("/") or value.startswith("//"):
        raise SyncError("The project base must be a root-relative URL path.")
    if any(character.isspace() or character in "'\"\\" for character in value):
        raise SyncError("The project base contains an unsafe character.")

    parsed = urllib.parse.urlsplit(value)
    if parsed.scheme or parsed.netloc or parsed.query or parsed.fragment:
        raise SyncError("The project base cannot contain a host, query, or fragment.")
    if any(segment in {".", ".."} for segment in parsed.path.split("/")):
        raise SyncError("The project base cannot contain dot-path segments.")
    if parsed.path == "/":
        return "/"
    return "/" + parsed.path.strip("/") + "/"


def normalize_navbar(navbar: str, project_base: str) -> str:
    """Make upstream links safe when embedded at any depth under MOST."""

    project_base = normalize_project_base(project_base)
    link_rewrites = {
        "../MOST": project_base,
        "../MOST/": project_base,
        "./MOST": project_base,
        "./MOST/": project_base,
        "/MOST": project_base,
        "/MOST/": project_base,
        "../itsc24-rr-tutorial": "/itsc24-rr-tutorial/",
        "../itsc24-rr-tutorial/": "/itsc24-rr-tutorial/",
        "./awesome-rerite.html": "/awesome-rerite.html",
    }

    href_pattern = re.compile(r"href=(?P<quote>['\"])(?P<url>[^'\"]+)(?P=quote)")

    def replace_href(match: re.Match[str]) -> str:
        quote = match.group("quote")
        url = match.group("url")
        return f"href={quote}{link_rewrites.get(url, url)}{quote}"

    normalized = href_pattern.sub(replace_href, navbar).strip()
    required_fragments = (
        '<nav class="navbar">',
        'class="navbar-toggle"',
        'class="navbar-nav"',
        "document.querySelector('.navbar')",
    )
    missing = [fragment for fragment in required_fragments if fragment not in normalized]
    if missing:
        raise SyncError(
            "Upstream navbar structure changed; refusing to inject an unvalidated partial. "
            f"Missing: {', '.join(missing)}"
        )
    return normalized + "\n"


def extract_shared_css(styles: str) -> tuple[str, str]:
    navigation_index = styles.find(CSS_NAVIGATION_MARKER)
    container_index = styles.find(CSS_CONTAINER_MARKER)
    if navigation_index < 0 or container_index < 0 or navigation_index >= container_index:
        raise SyncError(
            "Upstream CSS section markers changed; expected Navigation before Container. "
            "No files were modified."
        )

    base_css = styles[:navigation_index].strip()
    navbar_css = styles[navigation_index:container_index].strip()
    # Preserve later top-level navbar overrides (the upstream homepage section
    # currently contains one global .navbar rule). Scoped page rules and other
    # components remain local to the upstream site.
    tail = styles[container_index:]
    late_navbar_rules = re.findall(
        r"(?ms)^\.navbar[ \t]*\{[^{}]*\}", tail
    )
    if late_navbar_rules:
        navbar_css += (
            "\n\n/* Later upstream navbar overrides */\n"
            + "\n\n".join(rule.strip() for rule in late_navbar_rules)
        )
    if ":root" not in base_css or ".navbar" not in navbar_css:
        raise SyncError(
            "Upstream shared CSS failed validation; expected :root tokens and .navbar rules."
        )
    return (
        GENERATED_HEADER + base_css + "\n",
        GENERATED_HEADER + navbar_css + "\n",
    )


def page_targets() -> list[Path]:
    missing = [path for path in REQUIRED_TARGETS if not path.is_file()]
    if missing:
        names = ", ".join(str(path.relative_to(ROOT)) for path in missing)
        raise SyncError(f"Required HTML target(s) missing: {names}")

    generated_blog_pages = sorted((ROOT / "blog").glob("*.html"))
    targets = list(REQUIRED_TARGETS) + generated_blog_pages
    return list(dict.fromkeys(targets))


def relative_asset_prefix(path: Path) -> str:
    # Blog templates render into blog/, so both templates and generated pages
    # need a path relative to that output directory.
    return (
        "../assets/rerite"
        if ROOT / "blog" in path.parents
        else "assets/rerite"
    )


def marked_block(start: str, content: str, end: str, indent: str = "") -> str:
    indented_content = "\n".join(
        indent + line if line else line for line in content.rstrip().splitlines()
    )
    return f"{indent}{start}\n{indented_content}\n{indent}{end}"


def replace_existing_marked_block(
    text: str, start: str, content: str, end: str, *, path: Path
) -> str | None:
    start_count = text.count(start)
    end_count = text.count(end)
    if start_count == 0 and end_count == 0:
        return None
    if start_count != 1 or end_count != 1 or text.index(start) > text.index(end):
        raise SyncError(f"Invalid sync markers in {path.relative_to(ROOT)}")

    pattern = re.compile(
        r"(?P<indent>^[ \t]*)"
        + re.escape(start)
        + r".*?^[ \t]*"
        + re.escape(end),
        re.DOTALL | re.MULTILINE,
    )
    match = pattern.search(text)
    if not match:
        raise SyncError(f"Could not parse sync markers in {path.relative_to(ROOT)}")
    replacement = marked_block(start, content, end, match.group("indent"))
    return text[: match.start()] + replacement + text[match.end() :]


def remove_legacy_nav_scripts(text: str) -> str:
    script_pattern = re.compile(r"\s*<script\b[^>]*>.*?</script>", re.DOTALL | re.IGNORECASE)
    matches = list(script_pattern.finditer(text))
    for match in reversed(matches):
        script = match.group(0)
        if (
            "document.querySelector('.navbar')" in script
            and ".navbar-toggle" in script
        ):
            text = text[: match.start()] + text[match.end() :]
    return text


def update_navbar(text: str, navbar: str, *, path: Path) -> str:
    existing = replace_existing_marked_block(
        text, NAV_START, navbar, NAV_END, path=path
    )
    if existing is not None:
        return existing

    text = remove_legacy_nav_scripts(text)
    nav_pattern = re.compile(
        r"(?P<indent>^[ \t]*)<nav\s+class=(['\"])navbar\2[^>]*>.*?</nav>",
        re.DOTALL | re.IGNORECASE | re.MULTILINE,
    )
    matches = list(nav_pattern.finditer(text))
    if len(matches) != 1:
        raise SyncError(
            f"Expected exactly one legacy navbar in {path.relative_to(ROOT)}, "
            f"found {len(matches)}. Add {NAV_START} and {NAV_END} markers manually."
        )
    match = matches[0]
    replacement = marked_block(NAV_START, navbar, NAV_END, match.group("indent"))
    return text[: match.start()] + replacement + text[match.end() :]


def update_style_links(text: str, *, path: Path) -> str:
    prefix = relative_asset_prefix(path)
    links = (
        f'<link rel="stylesheet" href="{prefix}/rerite-base.css">\n'
        f'<link rel="stylesheet" href="{prefix}/rerite-navbar.css">'
    )
    existing = replace_existing_marked_block(
        text, STYLES_START, links, STYLES_END, path=path
    )
    if existing is not None:
        return existing

    stylesheet_pattern = re.compile(
        r"^(?P<indent>[ \t]*)<link\b[^>]*href=(['\"])[^'\"]*mostyles\.css\2[^>]*>[ \t]*$",
        re.MULTILINE | re.IGNORECASE,
    )
    match = stylesheet_pattern.search(text)
    if not match:
        raise SyncError(
            f"Could not find the mostyles.css link in {path.relative_to(ROOT)}."
        )
    indent = match.group("indent")
    block = marked_block(STYLES_START, links, STYLES_END, indent)
    return text[: match.end()] + "\n" + block + text[match.end() :]


def update_page(text: str, navbar: str, *, path: Path) -> str:
    text = update_style_links(text, path=path)
    return update_navbar(text, navbar, path=path)


def load_manifest() -> dict[str, object]:
    if not MANIFEST_PATH.is_file():
        return {}
    try:
        return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def build_manifest(
    snapshot: Snapshot,
    navbar: str,
    base_css: str,
    navbar_css: str,
    existing_manifest: dict[str, object],
) -> str:
    source_hashes = {
        "navbar.html": sha256_text(snapshot.navbar),
        "styles.css": sha256_text(snapshot.styles),
    }
    previous_hashes = existing_manifest.get("source_sha256")
    if previous_hashes == source_hashes:
        source_commit = str(existing_manifest.get("source_commit") or snapshot.commit)
    else:
        source_commit = snapshot.commit

    manifest = {
        "schema": 1,
        "upstream_repository": UPSTREAM_REPOSITORY,
        "source_ref": snapshot.ref,
        "source_commit": source_commit,
        "source_sha256": source_hashes,
        "generated_sha256": {
            "navbar.html": sha256_text(navbar),
            "rerite-base.css": sha256_text(base_css),
            "rerite-navbar.css": sha256_text(navbar_css),
        },
    }
    return json.dumps(manifest, indent=2, sort_keys=True) + "\n"


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        destination_mode = stat.S_IMODE(path.stat().st_mode)
    except FileNotFoundError:
        destination_mode = 0o644

    temporary_name = ""
    try:
        with tempfile.NamedTemporaryFile(
            "w", encoding="utf-8", dir=path.parent, delete=False, newline="\n"
        ) as temporary:
            temporary.write(content)
            temporary_name = temporary.name
        os.chmod(temporary_name, destination_mode)
        os.replace(temporary_name, path)
    finally:
        if temporary_name and os.path.exists(temporary_name):
            os.unlink(temporary_name)


def read_if_present(path: Path) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except FileNotFoundError:
        return None


def plan_updates(snapshot: Snapshot, project_base: str) -> dict[Path, str]:
    navbar = normalize_navbar(snapshot.navbar, project_base)
    base_css, navbar_css = extract_shared_css(snapshot.styles)
    existing_manifest = load_manifest()

    expected: dict[Path, str] = {
        NAVBAR_ASSET: navbar,
        BASE_CSS_ASSET: base_css,
        NAVBAR_CSS_ASSET: navbar_css,
    }
    for path in page_targets():
        current = path.read_text(encoding="utf-8")
        expected[path] = update_page(current, navbar, path=path)

    expected[MANIFEST_PATH] = build_manifest(
        snapshot, navbar, base_css, navbar_css, existing_manifest
    )
    return expected


def display_path(path: Path) -> str:
    return str(path.relative_to(ROOT))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Check or apply RERITE navbar and shared-style updates."
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--check",
        action="store_true",
        help="report updates without modifying files (default)",
    )
    mode.add_argument(
        "--apply",
        action="store_true",
        help="apply updates to vendored assets and marked HTML pages",
    )
    parser.add_argument(
        "--source-dir",
        type=Path,
        help="read navbar.html and styles.css from a local upstream clone",
    )
    parser.add_argument(
        "--ref",
        default=DEFAULT_REF,
        help=f"remote upstream Git ref to fetch (default: {DEFAULT_REF})",
    )
    parser.add_argument(
        "--project-base",
        default="/MOST/",
        help="deployed project base path used in shared links (default: /MOST/)",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    try:
        if args.source_dir and args.ref != DEFAULT_REF:
            raise SyncError("--ref cannot be combined with --source-dir.")
        snapshot = (
            load_local_snapshot(args.source_dir)
            if args.source_dir
            else load_remote_snapshot(args.ref)
        )
        expected = plan_updates(snapshot, args.project_base)
        changed = [
            path for path, content in expected.items() if read_if_present(path) != content
        ]
    except (OSError, SyncError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 2

    short_commit = snapshot.commit[:12]
    print(f"RERITE source: {snapshot.source}")
    print(f"Snapshot: {short_commit}")

    if not changed:
        print("Shared navigation and styles are up to date.")
        return 0

    print("Updates available:")
    for path in changed:
        print(f"  - {display_path(path)}")

    if not args.apply:
        print("Run `python sync_rerite.py --apply` to apply these updates.")
        return 1

    try:
        for path in changed:
            atomic_write(path, expected[path])
    except OSError as error:
        print(f"error: could not write synchronized files: {error}", file=sys.stderr)
        return 2

    print(f"Applied {len(changed)} synchronized file update(s).")
    print("Review with `git diff --stat` and preview the site before committing.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
